resource "test0_instance" "foo" {}
resource "test1_instance" "foo" {}
resource "test2_instance" "foo" {}
resource "test3_instance" "foo" {}
resource "test4_instance" "foo" {}
resource "test5_instance" "foo" {}
resource "test6_instance" "foo" {}
resource "test7_instance" "foo" {}
resource "test8_instance" "foo" {}
resource "test9_instance" "foo" {}
