// Code generated by "stringer -type=OperationType operation_type.go"; DO NOT EDIT.

package backend

import "fmt"

const _OperationType_name = "OperationTypeInvalidOperationTypeRefreshOperationTypePlanOperationTypeApply"

var _OperationType_index = [...]uint8{0, 20, 40, 57, 75}

func (i OperationType) String() string {
	if i >= OperationType(len(_OperationType_index)-1) {
		return fmt.Sprintf("OperationType(%d)", i)
	}
	return _OperationType_name[_OperationType_index[i]:_OperationType_index[i+1]]
}
