// Code generated by "stringer -type=countHookAction hook_count_action.go"; DO NOT EDIT.

package local

import "fmt"

const _countHookAction_name = "countHookActionAddcountHookActionChangecountHookActionRemove"

var _countHookAction_index = [...]uint8{0, 18, 39, 60}

func (i countHookAction) String() string {
	if i >= countHookAction(len(_countHookAction_index)-1) {
		return fmt.Sprintf("countHookAction(%d)", i)
	}
	return _countHookAction_name[_countHookAction_index[i]:_countHookAction_index[i+1]]
}
