// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package tfdiags

import "fmt"

const (
	_Severity_name_0 = "Error"
	_Severity_name_1 = "Warning"
)

var (
	_Severity_index_0 = [...]uint8{0, 5}
	_Severity_index_1 = [...]uint8{0, 7}
)

func (i Severity) String() string {
	switch {
	case i == 69:
		return _Severity_name_0
	case i == 87:
		return _Severity_name_1
	default:
		return fmt.Sprintf("Severity(%d)", i)
	}
}
