# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

name: equivalence-test
description: "Execute the suite of Terraform equivalence tests in testing/equivalence-tests and update the golden files."
inputs:
  target-equivalence-test-version:
    description: "The version of the Terraform equivalence tests to use."
    default: "0.3.0"
  target-os:
    description: "Current operating system"
    default: "linux"
  target-arch:
    description: "Current architecture"
    default: "amd64"
  current-branch:
    description: "What branch are we currently on?"
    required: true
  new-branch:
    description: "Name of new branch to be created for the review."
    required: true
  reviewers:
    description: "Comma-separated list of GitHub usernames to request review from."
    required: true
  message:
    description: "Message to include in the commit."
    required: true
runs:
  using: "composite"
  steps:

    - name: "download equivalence test binary"
      shell: bash
      run: |
        ./.github/scripts/equivalence-test.sh download_equivalence_test_binary \
          ${{ inputs.target-equivalence-test-version }} \
          ./bin/equivalence-tests \
          ${{ inputs.target-os }} \
          ${{ inputs.target-arch }}

    - name: Build terraform
      shell: bash
      run: ./.github/scripts/equivalence-test.sh build_terraform_binary ./bin/terraform

    - name: "run and update equivalence tests"
      id: execute
      shell: bash
      run: |
        ./bin/equivalence-tests update \
          --tests=testing/equivalence-tests/tests \
          --goldens=testing/equivalence-tests/outputs \
          --binary=$(pwd)/bin/terraform
        
        git add --intent-to-add testing/equivalence-tests/outputs
        changed=$(git diff --quiet -- testing/equivalence-tests/outputs || echo true)
        echo "changed=$changed" >> "${GITHUB_OUTPUT}"

    - name: "branch, commit, and push changes"
      if: steps.execute.outputs.changed == 'true'
      shell: bash
      run: |
        git config user.name "hc-github-team-tf-core"
        git config user.email "github-team-tf-core@hashicorp.com"
        git checkout -b ${{ inputs.new-branch }}
        git add testing/equivalence-tests/outputs
        git commit -m "Update equivalence test golden files."
        git push --set-upstream origin ${{ inputs.new-branch }}
          
    - name: "create pull request"
      if: steps.execute.outputs.changed == 'true'
      shell: bash
      run: |
        gh pr create \
          --draft \
          --base ${{ inputs.current-branch }} \
          --head ${{ inputs.new-branch }} \
          --title "Update equivalence test golden files" \
          --body '${{ inputs.message }}' \
          --reviewer ${{ inputs.reviewers }}
