// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: BUSL-1.1

syntax = "proto3";

package proto;

option go_package = "github.com/hashicorp/terraform-policy-plugin/proto";

service CallbackService {
  rpc GetResources(GetResourcesRequest) returns (GetResourcesResponse);
  rpc RelatedResources(RelatedResourcesRequest) returns (RelatedResourcesResponse);
  rpc GetDataSource(GetDataSourceRequest) returns (GetDataSourceResponse);
}

message GetResourcesRequest {
  string type = 1;
  bytes attributes = 2;
  // evaluation_request_id is the ID of the policy evaluation request that is
  // making this callback request.
  uint32 evaluation_request_id = 3;

 
}

message GetResourcesResponse {
  repeated bytes results = 1;
  // partial means that the request encountered unknown objects during evaluation,
  // and the results may be incomplete.
  bool partial = 2;
}


message RelatedResourcesRequest {
    // Direction indicates the direction of the reference relative to the subject.
    enum Direction {
      Invalid = 0;
      // Direction is Inbound if the related attribute is a reference to the subject.
      Inbound = 1;

      // Direction is Outbound if the subject is a reference to the related attribute.
      Outbound = 2;
    }

  message Relationship {
    // type is the type of the related resource
    string type = 1;
    repeated AttributePair attribute_pairs = 2;
    Relationship nested = 3;
    Direction direction = 4;
  }

  message AttributePair {
    string subject_attribute = 1;
    string related_attribute = 2;
  }

  string type = 1;
  Relationship relationship = 2;
  // evaluation_request_id is the ID of the policy evaluation request that is
  // making this callback request.
  uint32 evaluation_request_id = 3;
}

message RelatedResourcesResponse {
  repeated bytes results = 1;
  // partial means that Terraform could not conclusively determine whether the
  // relationship exists for all candidates.
  bool partial = 2;
}

message GetDataSourceRequest {
  string type = 1;
  bytes config = 2;
  // evaluation_request_id is the ID of the policy evaluation request that is
  // making this callback request.
  uint32 evaluation_request_id = 3;
}

message GetDataSourceResponse {
  bytes result = 1;
  // deferred indicates that the data source read was deferred during evaluation.
  bool deferred = 2;
}
