source 'https://rubygems.org'

gem "less", "~> 2.5.0"
gem "middleman", "~> 3.3.2"

gem "middleman-minify-html", "~> 3.1.1"
gem "rack-contrib", "~> 1.1.0"
gem "redcarpet", "~> 3.0.0"
gem "therubyracer", "~> 0.12.0"
gem "thin", "~> 1.5.0"

group :development do
  gem "highline", "~> 1.6.15"
end
